### DISCUSSION TITLE
v17: Default repository and activeProfile configuration

### DISCUSSION THREAD

**Discussion by zteater** [whelk-io/maven-settings-xml-action#107] [General]
Maven Central is now an optional repository. Override this default configuration at `repository`.

```yaml
- name: maven-settings-xml-action
  uses: whelk-io/maven-settings-xml-action@v17
  with:
    repositories: |
      [
        {
          "id": "some-repository",
          "name": "some-repository-name",
          "url": "http://some.repository.url",
          "releases": {
            "enabled": "true"
          },
          "snapshots": {
            "enabled": "false"
          }
        }
      ]
```

When `repository` is not configured, the following default is applied to `settings.xml`:

```xml
<profiles>
  <profile>
    <id>github</id>
    <repositories>
      <repository>
        <id>central</id>
        <name>Maven Central</name>
        <url>https://repo1.maven.org/maven2</url>
        <releases>
          <enabled>true</enabled>
        </releases>
        <snapshots>
          <enabled>false</enabled>
        </snapshots>
      </repository>
    </repositories>
    <pluginRepositories/>
  </profile>
</profiles>
```

`github` is now an optional `activeProfile`. Override this default `activeProfile` at `active_profiles`.

```yaml
- name: maven-settings-xml-action
  uses: whelk-io/maven-settings-xml-action@v17
  with:
    active_profiles: |
      [ 
        "some-profile"
      ]
```

When `active_profiles` is not configured, the following default is applied to `settings.xml`:

```xml
<activeProfiles>
  <activeProfile>github</activeProfile>
</activeProfiles>
```

Updated `README.md` with local setup and contributing guidelines.

<hr /><em>This discussion was created from the release <a href='https://github.com/whelk-io/maven-settings-xml-action/releases/tag/17'>17: Merge pull request #105 from whelk-io/develop</a>.</em>
