### ISSUE TITLE
Add support for repository updatePolicy

### ISSUE THREAD

**Issue by TuomasKiviaho** [whelk-io/maven-settings-xml-action#126]
https://maven.apache.org/ref/3.8.2/maven-settings/settings.html

`releases.updatePolicy` and/or `snapshots.updatePolicy` as `always`/`never`/... are handy from time to time. These would provide more fine grained control that the `mvn -U` switch

**Comment by zteater** [comment]
@TuomasKiviaho this is supported already, although not properly documented. I added a unit test for this: https://github.com/whelk-io/maven-settings-xml-action/commit/98d6a3ab0e1b5510de52855e93125c1ed6578124

Essentially you can configure it like this:
```yaml
- name: maven-settings-xml-action
  uses: whelk-io/maven-settings-xml-action@v20
  with:
    repositories: |
      [
        {
          "id": "central",
          "name": "Maven Central",
          "url": "https://repo1.maven.org/maven2",
          "releases": {
            "enabled": "true",
            "updatePolicy": "always",
          },
          "snapshots": {
            "enabled": "false"
          }
        }
      ]

```
