### ISSUE TITLE
Use secrets in template 

### ISSUE THREAD

**Issue by hiteshbal91dp** [whelk-io/maven-settings-xml-action#161]
- We want to attach username and password from secrets. As follows.
```
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          output_file: settings.xml
          repositories: '[{"id":"","name":"","url":""]'
          plugin_repositories: '[{"id":"","name":"","url":""]'
          servers: '[{"id":"central","username":"${{secrets.JFROG_READ_USER}}","password":"${{secrets.JFROG_READ_PASS}}"},{"id":"snapshots","username":"${{secrets.JFROG_READ_USER}}","password":"${{secrets.JFROG_READ_PASS}}"}]'
```

But above one is not working, can you please help me resolve above issue.
