### ISSUE TITLE
Problem with maven-settings-xml-action regarding repository and pluginRepository for defined profile

### ISSUE THREAD

**Issue by alejos97** [whelk-io/maven-settings-xml-action#170]
For this input:

name: Configure Maven
      uses: whelk-io/maven-settings-xml-action@v22
      with:
          active_profiles: >
            [
              "build.env.corporate"
            ]
          servers: >
            [
              {
                "id": "central",
                "username": "dgvt_dev",
                "password": "xxxxx"
              },
              {
                "id": "proj-releases",
                "username": "dgvt_deploy",
                "password": "xxxxx"
              },
              {
                "id": "proj-snapshots",
                "username": "dgvt_deploy",
                "password": "xxxxx"
              },
              {
                "id": "proj-site",
                "username": "dgvt_deploy",
                "password": "xxxxx"
              }
            ]
          profiles: >
            [
              {
                "id": "build.env.corporate",
                "activation": {
                    "activeByDefault": "false"
                },
                "repositories": {
                  "repository": {
                   "id": "central",
                   "url": "https://itm-ci.bmwgroup.net/nexus/repository/dgvt-repositories",
                   "releases": {
                     "enabled": "true"
                   },
                   "snapshots": {
                     "enabled": "true",
                     "updatePolicy": "always"
                   }
                  }
                },
                "pluginRepositories": {
                  "pluginRepository": {
                   "id": "central",
                   "url": "https://itm-ci.bmwgroup.net/nexus/repository/dgvt-repositories",
                   "releases": {
                     "enabled": "true"
                   },
                   "snapshots": {
                     "enabled": "true"
                   }
                  }
                },
                 "properties": {
                  "repository.proj-releases.url": "https://itm-ci.bmwgroup.net/nexus/repository/dgvt-releases",
                  "repository.proj-snapshots.url": "https://itm-ci.bmwgroup.net/nexus/repository/dgvt-snapshots",
                  "repository.proj-site.url": "https://itm-ci.bmwgroup.net/nexus/repository/dgvt-site"
                }
              }
            ]
          output_file: .m2/settings.xml
    - run: |
          cat .m2/settings.xml

I only get this output:

  <activeProfiles>
    <activeProfile>
      build.env.corporate
    </activeProfile>
  </activeProfiles>
  <profiles>
    <profile>
      <id>
        github
      </id>
      <repositories>
        <repository>
          <id>
            central
          </id>
          <name>
            Maven Central
          </name>
          <url>
            https://repo1.maven.org/maven2
          </url>
          <releases>
            <enabled>
              true
            </enabled>
          </releases>
          <snapshots>
            <enabled>
              false
            </enabled>
          </snapshots>
        </repository>
      </repositories>
      <pluginRepositories/>
    </profile>
    <profile>
      <id>
        build.env.corporate
      </id>
      <activation>
        <activeByDefault>
          false
        </activeByDefault>
      </activation>
      <properties>
        <repository.proj-releases.url>
          https://itm-ci.bmwgroup.net/nexus/repository/dgvt-releases
        </repository.proj-releases.url>
        <repository.proj-snapshots.url>
          https://itm-ci.bmwgroup.net/nexus/repository/dgvt-snapshots
        </repository.proj-snapshots.url>
        <repository.proj-site.url>
          https://itm-ci.bmwgroup.net/nexus/repository/dgvt-site
        </repository.proj-site.url>
      </properties>
      <repositories>
        <repository>
          **[object Object]**
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          **[object Object]**
        </pluginRepository>
      </pluginRepositories>
    </profile>
  </profiles>
  <servers>
    <server>
      <id>
        central
      </id>
      <username>
        dgvt_dev
      </username>
      <password>
        xxxxx
      </password>
    </server>
    <server>
      <id>
        proj-releases
      </id>
      <username>
        dgvt_deploy
      </username>
      <password>
        xxxxx
      </password>
    </server>
    <server>
      <id>
        proj-snapshots
      </id>
      <username>
        dgvt_deploy
      </username>
      <password>
        xxxxx
      </password>
    </server>
    <server>
      <id>
        proj-site
      </id>
      <username>
        dgvt_deploy
      </username>
      <password>
        xxxxx
      </password>
    </server>
  </servers>
  <mirrors/>
  <pluginGroups/>
  <proxies/>
</settings>

And this error message:

Error:  Error executing Maven.
Error:  5 problems were encountered while building the effective settings
Warning:  expected START_TAG or END_TAG not TEXT (position: TEXT seen ...<repository>\n          [object Object]\n        </... @60:11)  @ C:\actions-runner\_work\dgv_cm_parent\dgv_cm_parent\.m2\settings.xml, line 60, column 11
Error:  'profiles.profile[build.env.corporate].repositories.repository.id' is missing @ C:\actions-runner\_work\dgv_cm_parent\dgv_cm_parent\.m2\settings.xml
Error:  'profiles.profile[build.env.corporate].repositories.repository.url' is missing @ C:\actions-runner\_work\dgv_cm_parent\dgv_cm_parent\.m2\settings.xml
Error:  'profiles.profile[build.env.corporate].pluginRepositories.pluginRepository.id' is missing @ C:\actions-runner\_work\dgv_cm_parent\dgv_cm_parent\.m2\settings.xml
Error:  'profiles.profile[build.env.corporate].pluginRepositories.pluginRepository.url' is missing @ C:\actions-runner\_work\dgv_cm_parent\dgv_cm_parent\.m2\settings.xml
Error: Process completed with exit code 1.

When executing:

Run mvn -B --settings .m2/settings.xml package --file pom.xml

What do I do wrong?

**Comment by zteater** [comment]
The nested `<repositories>` and `<pluginRepositories>` fields are not currently supported on the `<profile>`, but enhancements are welcome!

In the interim, you might try a work-around to configure the `repositories` and `plugin_repositories` on the root.

```yaml
active_profiles: >
[
    "build.env.corporate"
]
servers: >
[
    {
        "id": "central",
        "username": "dgvt_dev",
        "password": "xxxxx"
    },
    {
        "id": "proj-releases",
        "username": "dgvt_deploy",
        "password": "xxxxx"
    },
    {
        "id": "proj-snapshots",
        "username": "dgvt_deploy",
        "password": "xxxxx"
    },
    {
        "id": "proj-site",
        "username": "dgvt_deploy",
        "password": "xxxxx"
    }
]
repositories: >
[
    {
        "id": "central",
        "name": "some-repository-name",
        "url": "https://itm-ci.bmwgroup.net/nexus/repository/dgvt-repositories",
        "releases": {
            "enabled": "true"
        },
        "snapshots": {
            "enabled": "true",
            "updatePolicy": "always"
        }
    }
]
plugin_repositories: >
[
    {
        "id": "central",
        "name": "some-plugin-repository-name",
        "url": "https://itm-ci.bmwgroup.net/nexus/repository/dgvt-repositories",
        "releases": {
            "enabled": "true"
        },
        "snapshots": {
            "enabled": "true"
        }
    }
]
profiles: >
[
    {
        "id": "build.env.corporate",
        "activation": {
            "activeByDefault": "false"
        },
        "properties": {
            "repository.proj-releases.url": "https://itm-ci.bmwgroup.net/nexus/repository/dgvt-releases",
            "repository.proj-snapshots.url": "https://itm-ci.bmwgroup.net/nexus/repository/dgvt-snapshots",
            "repository.proj-site.url": "https://itm-ci.bmwgroup.net/nexus/repository/dgvt-site"
        }
    }
]
```
