### ISSUE TITLE
Use environment variable

### ISSUE THREAD

**Issue by ThomasPires** [whelk-io/maven-settings-xml-action#39]
Hi,
Is it possible to include environnement variable ?
I tried many ways but I didn't succeed

**Comment by zteater** [comment]
@ThomasPires Good question, use of environment variables is supported. 

For example, configuring the servers like this:

```
- name: maven-settings-xml-action
  uses: whelk-io/maven-settings-xml-action@v4
  with:
    servers: '[{ "id": "some-server", "username": "some.user", "password": "${my.env.password}" }]'

```

Would produce a maven.settings like this:

```
<settings>
  <servers>
    <server>
      <id>some-server</id>
      <username>some.user</username>
      <password>${my.env.password}</password>
    </server>
  </servers>
</settings>
```
