### ISSUE TITLE
Snapshots and releases seems to be broken

### ISSUE THREAD

**Issue by gtournigand** [whelk-io/maven-settings-xml-action#54]
When creating a github actions using the snapshots and releases keys, the settings.xml file seems to be broken:

```yaml
name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v4
      with:
        repositories: '[{ "id": "maven-internal", "url": "https://maven.aaaaa.aa", "name": "maven-internal", "snapshots": {"enabled": "true"} }]'
    - name: Debug config
      run: cat /home/runner/.m2/settings.xml
```

Generates the following file:

```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                        http://maven.apache.org/xsd/settings-1.0.0.xsd">

  <activeProfiles>
    <activeProfile>github</activeProfile>
  </activeProfiles>

  <profiles>
    <profile>
      <id>github</id>
      <repositories>
        <repository>
          <id>central</id>
          <url>https://repo1.maven.org/maven2</url>
          <releases>
            <enabled>true</enabled>
          </releases>
          <snapshots>
            <enabled>false</enabled>
          </snapshots>
        </repository>
      <repository><id>maven-internal</id><url>https://maven.aaaaa.aa</url><name>maven-internal</name><snapshots>[object Object]</snapshots></repository></repositories>
      <pluginRepositories/>
    </profile>
  </profiles>

</settings>
```

When running maven (not depicted here)

```
expected START_TAG or END_TAG not TEXT (position: TEXT seen ...<snapshots>[object Object]</... @22:131)
```

Am I missing something ?

Thanks
